# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'lukaszPicker' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for lukaszPicker
  pod 'AKPickerView'

  target 'lukaszPickerTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'lukaszPicker-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for lukaszPicker-tvOS

  target 'lukaszPicker-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
